import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import TextInput from '@/components/TextInput'
import {
  useCallback,
  useEffect,
  useState,
} from 'react';
const inter = Inter({ subsets: ['latin'] })
// import ImageInput from '../components/ImageInput'
// import ExampleText from '../components/ExampleText'

//to be rewritten and stuff later but idc atm

export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Dongle" rel="stylesheet" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          anyone can cook!
        </h1>

       <TextInput placeholder="enter your text here" />
        <p className={styles.description}>
          <code className={styles.code}>tired of instant ramen, ubereats, and dining hall food? colette is here to help you meal prep and cook delicious meals at home!</code>
        </p>
      </main>
    </>
  )
}
