import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import TextInput from '@/components/TextInput'
import MainImage from '../components/MainImage'
import ChatBubble from '../components/ChatBubble'
import ChatWindow from '../components/ChatWindow'
import {
  useCallback,
  useEffect,
  useState,
} from 'react';
import { getMessages, sendMessage, addMessage, addNewMessage, createUser } from "@/utils/request";
const inter = Inter({ subsets: ['latin'] })
import { useQuery } from 'react-query';

//to be rewritten and stuff later but idc atm

export default function Home() {
  const [userId, setUserId ] = useState('');

  //begin by making a new User for MongoDB. 
  useEffect(() => {
    (async () => {
      const res = await createUser();
      setUserId(res.data._id);
    })();


  }, []);

  return (
    <>
      <Head>
        <title>anyone can cook!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Dongle" rel="stylesheet" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          anyone can cook!
        </h1>
        
        <MainImage src="./images/main.png" alt="main" />

          <div className={styles.chat}>
            <ChatBubble msg="oh you're a cook? okay then name every food" />
          </div>
          
          <div className={styles.input}>
          <TextInput placeholder="enter your message here" />
          </div>

      </main>
    </>
  )
}